config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "paintings#index"
  resources :paintings, only: [ :index, :create ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/painting.rb
class Painting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  def index
    @paintings = Painting.order(id: :desc)
  end

  def create
    @painting = Painting.create!
    redirect_to root_url, notice: "Painting created"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kamal 2 Rails Example</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paintings/_painting.html.erb
<div class="painting">
  <h4>Painting #<%= painting.id %></h4>

  <div class="frame">
    <% if painting.color? %>
      <div class="inside" style="background-color: <%= painting.color %>">
        <%= painting.color %>
      </div>
    <% else %>
      <div class="inside">
        Painting being painted, wait a few seconds…
      </div>
    <% end %>
  </div>
</div>

app/views/paintings/index.html.erb
<%= turbo_stream_from :paintings %>

<h1>Paintings</h1>

<p>
  Paintings are redrawn about every 5 seconds.
</p>

<%= button_to "Create Painting", paintings_path %>

<div id="paintings">
  <%= render @paintings %>
</div>